/**
 * Stage 4 harness: transport in isolation (§11.4 of docs/PLAN.md).
 *
 * Two tabs, PeerJS, bytes moving reliably. No fold, no tree, no spaces — this
 * exists so chunking and backpressure bugs present as transport bugs, and so
 * POC question 1 gets a number.
 *
 * Open in two tabs (or two machines), copy one peer id into the other, connect,
 * send a blob. The metrics dump at the bottom is the deliverable.
 */
import { hex, sha256 } from '../fold/index.js';
import { metrics } from '../net/metrics.js';
import { Transport, type BlobStore } from '../net/peer.js';
import { PeerJsSignalling } from '../net/peerjs-signalling.js';
import './app.css';

/** In-memory store; stage 4 does not touch IndexedDB. */
const held = new Map<string, Uint8Array>();
const store: BlobStore = {
  get: async (h) => held.get(h) ?? null,
  put: async (h, b) => void held.set(h, b),
};

const el = (id: string): HTMLElement => document.getElementById(id)!;
const log = (msg: string): void => {
  const line = document.createElement('div');
  line.textContent = `${new Date().toISOString().slice(11, 23)}  ${msg}`;
  el('log').prepend(line);
};

// PeerJS is used for discovery only; blob bytes go to the raw data channel.
const transport = new Transport(new PeerJsSignalling(), store, {
  onOpen: (p) => {
    log(`connected: ${p}`);
    render();
  },
  onClose: (p) => {
    log(`closed: ${p}`);
    render();
  },
  onError: (e) => log(`error: ${e}`),
  onProgress: (h, got, total) => {
    el('progress').textContent = `${h.slice(0, 8)}… ${got}/${total} chunks`;
  },
  onBlob: (h, bytes) => {
    log(`received ${bytes.length} bytes, hash verified ${h.slice(0, 8)}…`);
    render();
  },
  onNoBlob: (h) => log(`NOBLOB — no peer holds ${h.slice(0, 8)}…`),
  onIce: (p, state) => log(`ice ${p.slice(0, 8)}…: ${state}`),
});

document.getElementById('harness')!.innerHTML = `
  <div class="harness">
    <h1>Transport harness</h1>
    <p class="harness-note">
      Stage 4: transport in isolation. Open this page in two tabs, copy one peer id
      into the other, connect, then send a blob. Nothing here touches the fold.
    </p>

    <section>
      <h2>This peer</h2>
      <div class="harness-row">
        <code id="peerid">starting…</code>
        <button id="copyid" type="button">Copy id</button>
      </div>
    </section>

    <section>
      <h2>Connect</h2>
      <div class="harness-row">
        <input id="remote" type="text" placeholder="remote peer id" size="40">
        <button id="connect" type="button">Connect</button>
      </div>
      <div class="harness-row"><span id="peers">no peers</span></div>
    </section>

    <section>
      <h2>Blobs held</h2>
      <div class="harness-row">
        <input id="size" type="number" value="4" min="0" step="1" size="6">
        <span>MB of generated bytes</span>
        <button id="generate" type="button">Generate</button>
        <input id="file" type="file">
      </div>
      <ul id="blobs" class="harness-list"></ul>
    </section>

    <section>
      <h2>Fetch</h2>
      <p class="harness-note">
        A peer's version vector says which <em>events</em> it holds, never which
        <em>blobs</em> (§3.4) — so there is no discovery here. Generate a blob in
        the other tab, copy its hash, and paste it in. A hash no peer holds
        answers NOBLOB, which is the §8.2 <em>unavailable</em> state.
      </p>
      <div class="harness-row">
        <input id="wanthash" type="text" placeholder="blob hash to request" size="40">
        <button id="want" type="button">WANT</button>
        <span id="progress"></span>
      </div>
    </section>

    <section>
      <h2>Metrics — POC question 1</h2>
      <pre id="metrics" class="harness-metrics"></pre>
      <button id="copymetrics" type="button">Copy JSON</button>
    </section>

    <section>
      <h2>Log</h2>
      <div id="log" class="harness-log"></div>
    </section>
  </div>
`;

function render(): void {
  el('peers').textContent =
    transport.connectedPeers.length === 0
      ? 'no peers'
      : `connected: ${transport.connectedPeers.join(', ')}`;

  el('blobs').innerHTML = '';
  if (held.size === 0) {
    el('blobs').innerHTML = '<li class="harness-empty">none — generate or load a file</li>';
  }
  for (const [h, bytes] of held) {
    const li = document.createElement('li');
    li.innerHTML =
      `<code title="${h}">${h.slice(0, 16)}…</code> ` +
      `${(bytes.length / 1024 / 1024).toFixed(2)} MB `;

    const copy = document.createElement('button');
    copy.type = 'button';
    copy.textContent = 'Copy hash';
    copy.addEventListener('click', () => void navigator.clipboard.writeText(h));

    // The point of the harness is fetching, so make it one click from here.
    const ask = document.createElement('button');
    ask.type = 'button';
    ask.textContent = 'WANT from peer';
    ask.addEventListener('click', () => {
      (el('wanthash') as HTMLInputElement).value = h;
      log(`WANT ${h.slice(0, 16)}…`);
      transport.want(h);
    });

    li.append(copy, ' ', ask);
    el('blobs').append(li);
  }

  el('metrics').textContent = JSON.stringify(metrics.summary(), null, 2);
}

async function add(bytes: Uint8Array, label: string): Promise<void> {
  const h = hex(await sha256(bytes));
  held.set(h, bytes);
  log(`${label}: ${bytes.length} bytes, hash ${h.slice(0, 16)}…`);
  render();
}

el('generate').addEventListener('click', () => {
  const mb = Number((el('size') as HTMLInputElement).value);
  const bytes = new Uint8Array(Math.round(mb * 1024 * 1024));
  crypto.getRandomValues(bytes.subarray(0, Math.min(bytes.length, 65536)));
  // Fill the rest cheaply; random throughout is slow and not what is measured.
  for (let i = 65536; i < bytes.length; i++) bytes[i] = i % 251;
  void add(bytes, 'generated');
});

el('file').addEventListener('change', (e) => {
  const f = (e.target as HTMLInputElement).files?.[0];
  if (f === undefined) return;
  void f.arrayBuffer().then((b) => add(new Uint8Array(b), `loaded ${f.name}`));
});

el('connect').addEventListener('click', () => {
  const id = (el('remote') as HTMLInputElement).value.trim();
  if (id === '') return;
  log(`dialling ${id}…`);
  transport.connect(id).then(
    () => render(),
    (err) => {
      log(`connect failed: ${String(err)}`);
      render();
    },
  );
});

el('want').addEventListener('click', () => {
  const h = (el('wanthash') as HTMLInputElement).value.trim();
  if (h === '') return;
  log(`WANT ${h.slice(0, 16)}…`);
  transport.want(h);
});

el('copyid').addEventListener('click', () => {
  void navigator.clipboard.writeText(transport.peerId ?? '');
});

el('copymetrics').addEventListener('click', () => {
  void navigator.clipboard.writeText(metrics.toJSON());
});

transport.start().then(
  (id) => {
    el('peerid').textContent = id;
    log(`peer id ${id}`);
    render();
  },
  (err) => log(`failed to start: ${String(err)}`),
);

setInterval(render, 2000);
