/**
 * Regenerate packages/web/src/ui/icons.ts from lucide-static.
 *
 * Only the icons named here ship, so the app carries no runtime icon
 * dependency and no unused payload. Add a name below and run `npm run icons`.
 *
 * Lucide is ISC licensed; the generated file carries the attribution.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

/** Our name → lucide's file name. */
const WANTED = {
  plus: 'plus',
  x: 'x',
  share: 'share-2',
  folderPlus: 'folder-plus',
  trash: 'trash-2',
  copy: 'copy',
  download: 'download',
  upload: 'upload',
  // "Keep a copy of this space": mirroring blobs (§2.4).
  database: 'database',
  // These five were added to the generated file by hand and never to this
  // list, so the next regeneration silently dropped them. Anything the app
  // imports belongs here.
  arrowLeft: 'arrow-left',
  clipboard: 'clipboard',
  files: 'files',
  folder: 'folder',
  settings: 'settings',
  // A text document, editable in place (§3.8).
  fileText: 'file-text',
  eye: 'eye',
  eyeOff: 'eye-off',
  link: 'link',
  users: 'users',
  log: 'scroll-text',
  pencil: 'pencil',
  rotate: 'rotate-ccw',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
  activity: 'activity',
  gitFork: 'git-fork',
  radio: 'radio',
  fileQuestion: 'file-question-mark',
  boxes: 'boxes',
  logIn: 'log-in',
};

const HEADER = `/**
 * Icons, inlined from lucide-static (ISC).
 *
 * Only the icons this app uses are here, so there is no runtime dependency and
 * nothing unused ships. Each value is the *inner* markup of a 24×24 stroke
 * icon; \`<Icon>\` supplies the \`<svg>\` wrapper, so size and colour come from CSS
 * via \`currentColor\` rather than being baked in.
 *
 * Generated by scripts/icons.mjs — run \`npm run icons\` after adding a name
 * there rather than editing this file.
 *
 * Lucide is ISC licensed. Copyright (c) for portions of Lucide are held by
 * Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for
 * Lucide are held by Lucide Contributors 2022.
 */
export const icons = {
`;

const entries = [];
for (const [name, file] of Object.entries(WANTED)) {
  const path = `node_modules/lucide-static/icons/${file}.svg`;
  if (!existsSync(path)) {
    console.error(`missing: ${file}.svg`);
    process.exitCode = 1;
    continue;
  }
  const inner = readFileSync(path, 'utf8')
    .replace(/<svg[^>]*>/, '')
    .replace('</svg>', '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join(' ');
  entries.push(`  ${name}: \`${inner}\`,`);
}

writeFileSync(
  'packages/web/src/ui/icons.ts',
  `${HEADER}${entries.join('\n')}\n} as const;\n\nexport type IconName = keyof typeof icons;\n`,
);
console.log(`wrote ${entries.length} icons`);
